# Generated by Django 2.2.13 on 2020-06-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200612_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.BigIntegerField()),
                ('heart_points', models.BigIntegerField(blank=True, null=True)),
                ('hydration', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_score', models.BigIntegerField()),
            ],
        ),
    ]
